interface Insight {
  type: 'alert' | 'warning' | 'info' | 'trend';
  icon: string;
  message: string;
}

interface InsightsPanelProps {
  insights: Insight[];
  loading: boolean;
}

export default function InsightsPanel({ insights, loading }: InsightsPanelProps) {
  if (loading) {
    return (
      <div className="glass rounded-3xl p-8 flex flex-col items-center justify-center gap-4 min-h-[300px]">
        <div className="w-10 h-10 border-4 border-primary-500 border-t-transparent rounded-full animate-spin" />
        <p className="text-slate-500 font-bold text-sm animate-pulse tracking-widest uppercase">Analyzing Data...</p>
      </div>
    );
  }

  return (
    <div className="glass rounded-3xl overflow-hidden flex flex-col h-full border-white/20 dark:border-slate-800/50">
      <div className="p-6 bg-gradient-to-r from-primary-600/10 to-blue-500/10 border-b border-white/10 dark:border-slate-800/50">
        <h3 className="text-xl font-black text-slate-900 dark:text-white tracking-tight flex items-center gap-2">
          <svg className="w-5 h-5 text-primary-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
          </svg>
          Smart Insights
        </h3>
        <p className="text-[10px] font-bold text-slate-500 uppercase tracking-widest mt-1">Generated by SkyCast Engine</p>
      </div>

      <div className="p-6 space-y-4 overflow-y-auto max-h-[500px]">
        {insights.length === 0 ? (
          <div className="text-center py-12 space-y-4">
             <div className="w-16 h-16 bg-slate-100 dark:bg-slate-800 rounded-2xl mx-auto flex items-center justify-center text-slate-400">
                <svg className="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M20 13V6a2 2 0 00-2-2H6a2 2 0 00-2 2v7m16 0v5a2 2 0 01-2 2H6a2 2 0 01-2-2v-5m16 0h-2.586a1 1 0 00-.707.293l-2.414 2.414a1 1 0 01-.707.293h-3.172a1 1 0 01-.707-.293l-2.414-2.414A1 1 0 006.586 13H4" />
                </svg>
             </div>
             <p className="text-slate-500 text-sm font-medium italic">Scanning for weather patterns...</p>
          </div>
        ) : (
          insights.map((insight, index) => (
            <div 
              key={index}
              className={`p-4 rounded-2xl border transition-all hover:scale-[1.02] animate-slide-up bg-white/50 dark:bg-slate-800/20 ${getInsightStyles(insight.type)}`}
              style={{ animationDelay: `${index * 0.1}s` }}
            >
              <div className="flex items-start gap-3">
                <span className="text-2xl mt-0.5 filter drop-shadow-sm">{insight.icon}</span>
                <div className="space-y-1">
                  <div className="flex items-center gap-2">
                    <span className="text-[10px] font-black uppercase tracking-[0.15em] opacity-80">{insight.type}</span>
                  </div>
                  <p className="text-sm font-bold text-slate-800 dark:text-slate-200 leading-relaxed">
                    {insight.message}
                  </p>
                </div>
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
}

function getInsightStyles(type: string): string {
  switch (type) {
    case 'alert':
      return 'border-rose-200 dark:border-rose-900/30 text-rose-700 dark:text-rose-400 shadow-lg shadow-rose-500/5';
    case 'warning':
      return 'border-amber-200 dark:border-amber-900/30 text-amber-700 dark:text-amber-400 shadow-lg shadow-amber-500/5';
    case 'trend':
      return 'border-primary-200 dark:border-primary-900/30 text-primary-700 dark:text-primary-400 shadow-lg shadow-primary-500/5';
    default:
      return 'border-blue-200 dark:border-blue-900/30 text-blue-700 dark:text-blue-400 shadow-lg shadow-blue-500/5';
  }
}
